CREATE TABLE [dbo].[NC_MJST_SalesQuotationDocument](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SaleQuotationId] [int] NOT NULL,
	[DownloadId] [int] NOT NULL,
 CONSTRAINT [PK_NC_MJST_SalesQuotationDocument] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO